### ISSUE TITLE
Demo App:  Chat Input Allows White Spaces and Enables Send Button Without Text

### ISSUE THREAD

**Issue by SarathVSasikala** [MacPaw/OpenAI#101]
**Describe the bug**
The input text in text chats accepts text with white spaces, resulting in **chat bubbles with white spaces**. Additionally, users can click the **send button without entering any text,** causing the creation of empty chat bubbles and generating a response.

**To Reproduce**
1. Go to the demo app chats page
2. Input some text with white spaces
3. Press the send button
4. A chat bubble is created with spaces

**Expected behavior**
After clicking the send button, white spaces should be removed, resulting in chat bubbles without any white spaces.

**Screenshots**
![Simulator Screenshot - iPhone 15 - 2023-10-03 at 14 00 20](https://github.com/MacPaw/OpenAI/assets/146827282/d1bc5410-c615-40f9-a856-ec745eca8dac)

**Additional context**
The chat send button is currently enabled even with an empty chat.

**Comment by SarathVSasikala** [comment]
I recommend adding a validation in text input and send button. 

**Add extra validation in DetailView tapSendMessage function:**
```
let message = inputText.trimmingCharacters(in: .whitespacesAndNewlines)
        if message.isEmpty {
            return
        }
```
also, send button disabledcondition: 
`.disabled(inputText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)`

**Output:**


https://github.com/MacPaw/OpenAI/assets/146827282/2c719d74-b92a-4d8b-bdd7-f13f8e0cd203

**Comment by ingvarus-bc** [comment]
Thanks for your rising an issues and your contribution! 🔥
Closing the issue now
Will merge your PR today 🤝
