### ISSUE TITLE
`"The given data was not valid JSON."` Streaming Error

### ISSUE THREAD

**Issue by PallavAg** [MacPaw/OpenAI#103]
**Describe the bug**
I'm on version 0.2.4, while streaming responses I still seem to often be getting the following error:
`"The data couldn't be read because it isn't in the correct format."`

In the console the full output is:
`dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected end of file" UserInfo={NSDebugDescription=Unexpected end of file})))`

**To Reproduce**
I usually always get this output when asking GPT-3.5: `"Write 1 to 40 using bullet points"`

Edit: Opened a PR to fix this: #104

**Comment by LordMatalas** [comment]
9 hours ago I had exactly the same situation, noticed that after 30 minutes of inactivity on my app; I was able to get communication with the API without that error message. Now, I'm not experimenting this issue anymore. No changes were made on the app though.

**Comment by PallavAg** [comment]
Ths patch in #97 fixes it! This change would really help the library.

**Comment by mariusiordache** [comment]
I have the same issue. It happens very often. When will the fix be released?
