### ISSUE TITLE
Add support for new multimodal APIs

### ISSUE THREAD

**Issue by usagimaru** [MacPaw/OpenAI#113]
Are there any plans to support new APIs for multimodal?

- Text to speech - new API
https://platform.openai.com/docs/api-reference/audio/createSpeech
- Vision - new model and parameters for chat completions
https://platform.openai.com/docs/guides/vision
- DALL-E 3 - new model for image generation
https://platform.openai.com/docs/guides/images

**Comment by ingvarus-bc** [comment]
Hi, thanks for the issue!
> - Vision - new model and parameters for chat completions
> https://platform.openai.com/docs/guides/vision
> - DALL-E 3 - new model for image generation
> https://platform.openai.com/docs/guides/images

Are covered in [PR-115](https://github.com/MacPaw/OpenAI/pull/115)
And you are right, we'll need to add `Create Speech` API support. Thanks!

**Comment by ingvarus-bc** [comment]
@usagimaru, added `Create Speech` feature in [PR-120](https://github.com/MacPaw/OpenAI/pull/120)
