### ISSUE TITLE
Add response_format parameter to AudioTranscriptionQuery

### ISSUE THREAD

**Issue by usagimaru** [MacPaw/OpenAI#114]
OpenAI's transcriptions API has a `response_format` field that specifies the output format, but it does not seem to be supported by MacPaw's client.
https://platform.openai.com/docs/api-reference/audio/createTranscription

Is it possible to add a response_format property to AudioTranscriptionQuery?

**Comment by ingvarus-bc** [comment]
Hey, @usagimaru! 👋
Thank you for reaching out!
Thanks to @rawnly, we'll add this in the next release! 🙌
