### ISSUE TITLE
Can you all more models? 

### ISSUE THREAD

**Issue by wyk111wyk** [MacPaw/OpenAI#18]
<img width="682" alt="截屏2023-03-18 11 58 38" src="https://user-images.githubusercontent.com/8171481/226083844-470fcbbf-3ace-49e5-ba6e-b620ceaea305.png">

The same endpoint has supported all new models like gpt4, all can you make it customized to we can pass a string name for lastest model.

**Comment by Krivoblotsky** [comment]
Hey, @wyk111wyk. 
Model name is actually a string, so you can use it like this:
```
openAI.chats(query: .init(model: "gpt-4", messages: messages)) { }
```

**Comment by Krivoblotsky** [comment]
I will add constants "gpt-4*" constants shortly.

**Comment by wyk111wyk** [comment]
> I will add constants "gpt-4*" constants shortly. 

Thanks for your quick response. And sorry for my title typo.
