### ISSUE TITLE
AudioTranscription Fails

### ISSUE THREAD

**Issue by abegehr** [MacPaw/OpenAI#194]
**Describe the bug**
On the latest version 0.2.7, AudioTranscriptionQueries fail.

**To Reproduce**
Run an audio transcription with the following code:

```swift
let query = AudioTranscriptionQuery(file: data, fileType: .m4a, model: .whisper_1)
let result =  try await openAI.audioTranscriptions(query: query)
```

**Expected behavior**
I'd expect the transcription to run successfully.

**Desktop (please complete the following information):**
 - OS: macOS 14

**Additional context**
The error: `APIErrorResponse(error: OpenAI.APIError(message: "Invalid file format. Supported formats: [\'flac\', \'m4a\', \'mp3\', \'mp4\', \'mpeg\', \'mpga\', \'oga\', \'ogg\', \'wav\', \'webm\']", type: "invalid_request_error", param: nil, code: nil))`

I tried different values for fileType, however all fail with the same error. The failure occurs quite fast, so I'd assume it is a metadata check by OpenAI's API and not an issue with data.

Transcription worked on version 0.2.6 with the following code:

```swift
let query = AudioTranscriptionQuery(file: data, fileName: "record.m4a", model: .whisper_1)
let result = try await openAI.audioTranscriptions(query: query)
```

**Comment by abegehr** [comment]
For reference, I'm working around the issue by making the HTTP call using Vapor's req.client directly (this is working):

```swift
struct AudioTranscriptionRequestBody: Content {
    var file: File
    var model: String
    var prompt: String?
    var temperature: String?
}
let file = File(data: buffer, filename: "speech.m4a")
let body = AudioTranscriptionRequestBody(file: file, model: "whisper-1")
let res = try await req.client.post(.init(string: "https://api.openai.com/v1/audio/transcriptions")) { request in
    request.headers.bearerAuthorization = .init(
        token: openAI.configuration.token)
    request.headers.contentType = .formData
    try request.content.encode(body, as: .formData)
}
let result = try res.content.decode(AudioTranscriptionResult.self)
```

**Comment by pradeepb28** [comment]
I honestly don't know why they are mapping m4a file to mp4 type
![CleanShot 2024-04-07 at 15 13 05](https://github.com/MacPaw/OpenAI/assets/6823101/2b56fde5-c3cf-42ec-9baa-9cd39e4601bc)

**Comment by abegehr** [comment]
Relevant commit here: https://github.com/MacPaw/OpenAI/commit/905e31706d7ae6c9c3a851e6bf40bd36f41a87fb
It was committed by James J Kalafus, however he is not linked to a GitHub profile.

**Comment by Demircivi** [comment]
I created [a PR](https://github.com/MacPaw/OpenAI/pull/197) that addresses this issue.

**Comment by AT5HK** [comment]
Same issue please fix this, I had to remove it from SPM and add OpenAI locally to change the code and fix it.

**Comment by pradeepb28** [comment]
> Same issue please fix this, I had to remove it from SPM and add OpenAI locally to change the code and fix it.

Please reply your concern in the above PR to escalate the MacPaw team to merge it. (I did it)

**Comment by kalafus** [comment]
> Relevant commit here: https://github.com/MacPaw/OpenAI/commit/905e31706d7ae6c9c3a851e6bf40bd36f41a87fb
> 
> It was committed by xyzzy, however he is not linked to a GitHub profile. 

Context from the original PR author: .m4a is MP4-family (audio/mp4). Not substituting failed at the time, so a workaround was added; the later breakage aligns with backend changes, and I’m glad OpenAI fixed it.

Meta: my name shows up unlinked in the commit due to non-matching GitHub email. Reference here surfaced via search. If possible, @abegehr please de-personalize the issue text.
