### ISSUE TITLE
AudioTranscriptionQuery fails 

### ISSUE THREAD

**Issue by pradeepb28** [MacPaw/OpenAI#195]
**Describe the bug**
Try uploading .m4a to transcribe raw transcript it fails because of the following switch case where you can see .m4a is pointing to mp4 file type.
![CleanShot 2024-04-07 at 15 21 27](https://github.com/MacPaw/OpenAI/assets/6823101/5e2d66d7-f2a7-4787-b8f2-d0f63ccc6d06)

**Expected behavior**
Able to successfully upload m4a file and then able to successfully retrieve the transcript

**Comment by Demircivi** [comment]
I created [a PR](https://github.com/MacPaw/OpenAI/pull/197) that addresses this issue.

**Comment by sauravexodus** [comment]
The merged PR has another bug, the content type for `.m4a` files should be `audio/mpeg` instead of `audio/m4a`.
