### ISSUE TITLE
Argument 'messages' must precede argument 'model'

### ISSUE THREAD

**Issue by tonyhung21186** [MacPaw/OpenAI#208]
Getting this error for Chat after recent package update: Argument 'messages' must precede argument 'model'. Thought anyone? 

Code below:
let query = ChatQuery(model: .gpt3_5Turbo, messages: [.init(role: .user, content: "who are you")])

**Comment by tonyhung21186** [comment]
solved. 

 if let message = ChatQuery.ChatCompletionMessageParam(role: .user, content: prompt) {
            let query = ChatQuery(messages: [message], model: .gpt4_o)
           
            // This work to generate a complete response
  
        } else {
            print("Failed to create ChatCompletionMessageParam.")
        }

**Comment by fbukevin** [comment]
I fixed this issue with :
```swift
    let query = ChatQuery(messages: [.init(role: .user, content: prompt)!], model: .gpt3_5Turbo)
    openAI.chats(query: query) { result in
        print(result)
    }
````
