### ISSUE TITLE
Possibility to upload files

### ISSUE THREAD

**Issue by JohannesWi** [MacPaw/OpenAI#230]
At ChatGPT Web, it is possible to upload files and analyse them. Is it possible to do the same with this package? I couldn’t find a solution so far.

**Comment by SilverMarcs** [comment]
The api does not support this yet. You will have to implement tool calling in your application and read files with your own implementation and return back the response of the tool call yourself to the api

**Comment by JohannesWi** [comment]
Thanks a lot for your response! I will try to find a solution by my self :)
