### ISSUE TITLE
[Suggestion] Remove the test cases that makes real networking calls, and move them into a demo app.

### ISSUE THREAD

**Issue by DJBen** [MacPaw/OpenAI#25]
**Is your feature request related to a problem? Please describe.**
Automated tests are meant to be publicly accessible and run by CI; having test cases that needs `API_KEY` to make real network calls creates issues for CI pipeline.

**Describe the solution you'd like**
Remove the test cases that makes real networking calls, and move them into a demo app.

**Comment by DJBen** [comment]
Hi to address this and to improve general scalability of the library, I have a follow up PR https://github.com/DJBen/OpenAI/pull/1 that stacks on top of #24. Please take a look!

**Comment by Krivoblotsky** [comment]
Hey, @DJBen.
Thanks for the suggestion 👍 
I was in the middle of the implementation for the last week, so your issue motivated me to finish it today😄
My implementation overall looks almost the same as yours, but anyway I will appreciate any suggestions here:
https://github.com/MacPaw/OpenAI/pull/30

**Comment by Krivoblotsky** [comment]
#30 has been merged. Closing the issue. 
Thanks for the contribution 👍

**Comment by DJBen** [comment]
Hi @Krivoblotsky your change looks good! I like the fact that there's no nested types.
