### ISSUE TITLE
Please fix the error handling

### ISSUE THREAD

**Issue by IKorabel** [MacPaw/OpenAI#26]
How to get a more understandable description of error? I handle it but I see only the response with type of error

**Comment by Krivoblotsky** [comment]
Released with [0.0.7](https://github.com/MacPaw/OpenAI/releases/tag/0.0.7).
Feel free to re-open the issue if you still have any questions👌

**Comment by IKorabel** [comment]
How can I update the library in SPM? I'm trying but it doesn't work

**Comment by IKorabel** [comment]
What should I do in order to get normal answer from api?
![Simulator Screen Shot - iPhone 14 Pro - 2023-04-02 at 23 53 52](https://user-images.githubusercontent.com/43014903/229380955-d48d6e6b-c7d5-4136-b19d-81c7e2143fd0.png)

**Comment by Krivoblotsky** [comment]
> How can I update the library in SPM? I'm trying but it doesn't work

If you use Xcode, you should: 
1. Reset Package Caches from File -> Packages.
2. Update Packages to the Latest Version from File->Packages.
<img width="523" alt="Screenshot 2023-04-03 at 01 33 34" src="https://user-images.githubusercontent.com/1411778/229382738-ddbaf238-b84b-49bc-bcc6-b26826775b3e.png">
<img width="526" alt="Screenshot 2023-04-03 at 01 33 38" src="https://user-images.githubusercontent.com/1411778/229382743-da566207-2e08-41e5-b947-e45177515d75.png">

> What should I do in order to get normal answer from API?

Here is an example of `APIError` handling:
```swift
let openAI = OpenAI(apiToken: "wrong API key")
openAI.audioTransciptions(query: .init(file: data, fileName: "hello.m4a", model: .whisper_1)) { result in
    switch result {
    case .success(let audioResult):
        print(audioResult.text)
    case .failure(let error):
        if let apiResponse = error as? APIErrorResponse {
            print("Human readable error message: \(apiResponse.error.message)") //Human readable error message: Incorrect API key provided: wrong AP* key. You can find your API key at https://platform.openai.com/account/api-keys.
        } else {
            print("Handle generic error: \(error.localizedDescription)")
        }
    }
}
```
