### ISSUE TITLE
Customization api url

### ISSUE THREAD

**Issue by iHTCboy** [MacPaw/OpenAI#27]
Because of proxy or public service reasons, I want to relay processing requests and responses.

chat request:
```swift
    func chats(query: ChatQuery, timeoutInterval: TimeInterval = 60.0, completion: @escaping (Result<ChatResult, Error>) -> Void) {
        performRequest(request: Request<ChatResult>(body: query, url: .chats, timeoutInterval: timeoutInterval), completion: completion)
    }
```

change like this：

```swift
    func chats(query: ChatQuery, timeoutInterval: TimeInterval = 60.0, url: URL = .chats, completion: @escaping (Result<ChatResult, Error>) -> Void) {
        performRequest(request: Request<ChatResult>(body: query, url: url, timeoutInterval: timeoutInterval), completion: completion)
    }
```

**Comment by Krivoblotsky** [comment]
Hey, @iHTCboy.
Thanks for the contribution!
Could you provide a real-world example of when you need to change default API URLs? 
I don't see any mentions in OpenAI documentation on this. 
https://platform.openai.com/docs/introduction

**Comment by iHTCboy** [comment]
Hey, @Krivoblotsky
Like in China, we cannot access directly, we need to use a proxy to access openai.com, so we build a unified server to transfer requests, so we need to customize API URLs at this time.

**Comment by Krivoblotsky** [comment]
@DJBen, agree. 
Will add it shortly 👍. 

@iHTCboy please see #32. 
What do you think about adding `host` variable to the `OpenAI.Configuration`, so all public functions are clear and we don't need to add `url` to every new function, but you still have an ability to inject the host and have URLs like `https://you_host.com/v1/completions`?

**Comment by Krivoblotsky** [comment]
@DJBen @iHTCboy 
Please see https://github.com/MacPaw/OpenAI/pull/33

**Comment by iHTCboy** [comment]
@Krivoblotsky Thanks，create a tagged version if you can~ 😀

**Comment by Krivoblotsky** [comment]
@iHTCboy here you are:
https://github.com/MacPaw/OpenAI/releases/tag/0.0.8
