### ISSUE TITLE
Add Decoder Tests

### ISSUE THREAD

**Issue by SunburstEnzo** [MacPaw/OpenAI#41]
**Is your feature request related to a problem? Please describe.**
I've discovered an issue with ModelResult by having a unit test.

**Describe the solution you'd like**
Adding a set of decoder-related unit tests would ensure the models are correct when comparing with the expected json.

**Describe alternatives you've considered**
It would be handy to have examples in the sample project, but unit tests would still be the most optimum solution.

**Additional context**
My proposition is something similar to the below, but with varying examples for all supported endpoint results

`class OpenAITestsDecoder: XCTestCase`
        
    func testModelsSingle() async throws {
        let data = """
        {
          "data": [
            {
              "id": "gpt-3.5-turbo",
              "object": "model",
              "owned_by": "organization-owner"
            }
          ],
          "object": "list"
        }
        """.data(using: .utf8)!
        
        do {
            let decoded = try JSONDecoder().decode(ModelsResult.self, from: data)
            
            let mock = ModelsResult(data: [
                .init(id: .gpt3_5Turbo, object: "model", ownedBy: "organization-owner")
            ], object: "list")
            
            XCTAssertEqual(decoded, mock)
            
        } catch let error {
            XCTFail(error.localizedDescription)
        }
    }

**Comment by Krivoblotsky** [comment]
Thanks for your contribution, @SunburstEnzo!
