### ISSUE TITLE
Add image/edit

### ISSUE THREAD

**Issue by Krivoblotsky** [MacPaw/OpenAI#45]
Extend the library by adding image/edit capabilities

### Documentation
https://platform.openai.com/docs/api-reference/images/create-edit

**Comment by ingvarus-bc** [comment]
@Krivoblotsky there was no action taken to your:
> please remove the comment

I removed it, everything seems to work properly, I see an approve from you, closing the issue and merging the [PR-62](https://github.com/MacPaw/OpenAI/pull/62)
