### ISSUE TITLE
Can it be improved to allow more detailed monitoring of the status of URLSession connections?

### ISSUE THREAD

**Issue by usagimaru** [MacPaw/OpenAI#50]
`OpenAI.swift` uses its own URLSession internally, but I have a use-case where I want to monitor the progress of the session from the out side.

I mainly want to monitor the progress of "sending" and "receiving" by means of delegate, etc. Is it possible to improve the interface design to such a way?

- Change `init(configuration: Configuration, session: URLSessionProtocol)` to `public` access level.
- Provide the delegate protocol so that messages such as completed, sending, receiving, failure, etc. can be messaging to the outside scopes.
- Change the access level of the `session` property to `public`.

**Comment by DJBen** [comment]
@usagimaru See #54 I opened a PR for you.

**Comment by DJBen** [comment]
Hi @usagimaru We exposed the `init(configuration: Configuration, session: URLSessionProtocol) to public access level.` to public. Let me know if this suffices your need. You can pass your own session and observe from there.
