### ISSUE TITLE
Demoapp Xcode project is missing the openAI library

### ISSUE THREAD

**Issue by Shiny1708** [MacPaw/OpenAI#58]
**Describe the bug**
The demoapp xcode project is missing the openAI library in its dependency settings

**To Reproduce**
1. Try to build and run the demo App
2. You will get an error that the openAI library is missing

**Expected behavior**
Build is successful and app runs

**Screenshots**
![CleanShot 2023-04-18 at 22 43 35](https://user-images.githubusercontent.com/81536709/232900539-91675f88-0755-422c-b532-6bbcbcf604f5.png)

**Steps to fix**
To fix the issue and run the app, one has to add the library with the plus icon
![CleanShot 2023-04-18 at 22 44 41](https://user-images.githubusercontent.com/81536709/232900721-f20674d9-5712-46e2-b720-8f2d264d3290.png)

**Comment by DJBen** [comment]
@Shiny1708 How did you run the project? You should be able to run the app by opening the `Demo/DemoApp.xcodeproj`

**Comment by LawrenceNorman** [comment]
I ran into the same thing: x-xcode-log://FE44CE90-E58F-4283-99E9-88226A8B8F54 product 'OpenAI' required by package 'demochat' target 'DemoChat' not found.

**Comment by DJBen** [comment]
<img width="1512" alt="Screenshot 2023-04-20 at 1 03 11 PM" src="https://user-images.githubusercontent.com/2078653/233475557-e7ec357e-4ee4-4bbd-a817-71a4b519a8ee.png">

I removed the repo and did a fresh git clone, the static library seems to have been added. @LawrenceNorman can you screenshot what you see?

**Comment by Shiny1708** [comment]
@DJBen I just double clicked the project file in the Demo Folder. The issue is even tho the folder is in the openai folder, it doesnt seems to be imported correctly. Your screenshot shows what i mean. It worked after I added openai as a library in there as well but nit without it

**Comment by DJBen** [comment]
@Krivoblotsky Did you experience the probem when opening demo app?

**Comment by Krivoblotsky** [comment]
> @Krivoblotsky Did you experience the probem when opening demo app?

No, it's fine on my end
<img width="1512" alt="Screenshot 2023-04-21 at 00 12 39" src="https://user-images.githubusercontent.com/1411778/233488847-cfad30cd-b759-4ec0-87fa-a10acdded469.png">

**Comment by SunburstEnzo** [comment]
If you have both Xcode projects open it doesn't want to build, but quitting Xcode then reopening and only opening the Demo project seems to work for me.

<img width="665" alt="Screenshot 2023-04-21 at 1 40 12 pm" src="https://user-images.githubusercontent.com/1451896/233638815-18b99807-dc64-47b0-a192-4219a98edb32.png">

 Note that the OpenAI package dependency did not say "local" before, but now it does.
 
<img width="271" alt="Screenshot 2023-04-21 at 1 44 09 pm" src="https://user-images.githubusercontent.com/1451896/233639274-be69bf80-05a0-46d1-b89f-f245e04a018e.png">

**Comment by Shiny1708** [comment]
Thats gotta be the dumbest shit I‘ve ever seen. Thanks for figuring it out

**Comment by DJBen** [comment]
Thanks for clarifying. Can we close the issue?

**Comment by loongkobe** [comment]
experience the same probem when opening demo app
