### ISSUE TITLE
Create release for the latest version

### ISSUE THREAD

**Issue by Janldeboer** [MacPaw/OpenAI#6]
As the current release `0.0.1` is still based on the initial version, most changes aren't accessible when installing the package using the Swift package manager.

Note: I'm not quite familiar with how exactly release management is handled here, maybe changing the tag is enough?

**Comment by Krivoblotsky** [comment]
Hey, @Janldeboer 
Thanks for taking my attention to this 👍 
I intended to wait until some scope (like 2-3 features) is gathered 👌 
I've just [published](https://github.com/MacPaw/OpenAI/releases/tag/0.0.2 ) a new release, with all the changes from `main`.

By the way, there is an option in SPM to specify the target branch, not the tag, so you don't need to wait until the release is created to get all the changes from `main`.
```
dependencies: [
    .package(url: "https://github.com/MacPaw/OpenAI.git", .branch("main"))
]
```
Feel free to reopen issues if you have any questions. 
Thanks for your contribution 👍

**Comment by Janldeboer** [comment]
Thank you very much! This solved my problem.
