### ISSUE TITLE
Version 0.2.0 breaks example with completion

### ISSUE THREAD

**Issue by jean-bovet** [MacPaw/OpenAI#71]
**Describe the bug**
The latest version, 0.2.0, break the completion example, likely due to the stream being true and the decoding not expecting the JSON format which OpenAI returns.

**To Reproduce**
1. Create a new Xcode project
2. Use the example of the prompt in the README:
3. `let query = CompletionsQuery(model: .textDavinci_003, prompt: "What is 42?", temperature: 0, max_tokens: 100, top_p: 1, frequency_penalty: 0, presence_penalty: 0, stop: ["\\n"])
openAI.completions(query: query) { result in
  //Handle result here
}
//or
let result = try await openAI.completions(query: query)`
4. Run the example and observe the following error: 
5. `failure(Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 1, column 0." UserInfo={NSDebugDescription=Invalid value around line 1, column 0., NSJSONSerializationErrorIndex=0}))))
`

**Expected behavior**
Reverting to the version before 0.2.0 works fine with an expected result without error.

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1

**Comment by jean-bovet** [comment]
Thanks @Krivoblotsky for the quick turn-around. Much appreciated! May I suggest adding unit tests around this in the future?

**Comment by Krivoblotsky** [comment]
Sure, I’ll add it with next release 👌
