### ISSUE TITLE
Support new models (gpt-4-0613 and gpt-3.5-turbo-0613)

### ISSUE THREAD

**Issue by iTarek** [MacPaw/OpenAI#76]
Hello
We need support for the new Function calling.

> Developers can now describe functions to gpt-4-0613 and gpt-3.5-turbo-0613, and have the model intelligently choose to output a JSON object containing arguments to call those functions. This is a new way to more reliably connect GPT's capabilities with external tools and APIs.

[Function calling and other API updates](https://openai.com/blog/function-calling-and-other-api-updates)

**Comment by ljoukov** [comment]
https://github.com/MacPaw/OpenAI/pull/77

**Comment by ljoukov** [comment]
Implementation of functions support: https://github.com/MacPaw/OpenAI/pull/78

**Comment by iTarek** [comment]
Thank you. When can we expect these features? I am very excited to try the new functions.

**Comment by Krivoblotsky** [comment]
Merged, thanks @ljoukov 👍
