### ISSUE TITLE
Add example project

### ISSUE THREAD

**Issue by Krivoblotsky** [MacPaw/OpenAI#8]
Adding an example project that demonstrates library usage would be awesome. Maybe some chat-based UX, but not required. 
iOS/macOS

**Comment by DJBen** [comment]
Hi @Krivoblotsky if you are not on this yet, I can finish this by end of the week. Do you think it's fine delegating this to me?

**Comment by Krivoblotsky** [comment]
Hi, @DJBen.
Sure thing, it would be awesome 🔥

**Comment by Krivoblotsky** [comment]
Thanks!

**Comment by Krivoblotsky** [comment]
Thanks!
