### ISSUE TITLE
Add models 

### ISSUE THREAD

**Issue by Krivoblotsky** [MacPaw/OpenAI#9]
Extend the library by adding `models` API call support so it gives the ability to retrieve the models' list. 
https://platform.openai.com/docs/api-reference/models

**Comment by SunburstEnzo** [comment]
Hi @Krivoblotsky, I hope you don't mind but I gave this a go in #38, do let me know if anything is missing! I've really enjoyed looking through the project and I'm glad it exists, and happy to accommodate any changes.

**Comment by Krivoblotsky** [comment]
Hey, @SunburstEnzo!
I have just merged it, everything is perfect 🔥 
Thanks for your contribution!

**Comment by SunburstEnzo** [comment]
That's great, I'm happy to help, thank you!
